#include <catch2/catch_test_macros.hpp>

#include <sstream>

#include "fastdicomattrs/parse.hpp"
#include "fixture_builder.hpp"

// WriteResult::source_backed_value_bytes / regenerated_value_bytes -- the
// concrete number behind the README's "quantify byte-level preservation of
// untouched content" success criterion. See write_result.hpp for exactly
// what is and isn't counted (value payloads and Pixel Data; never
// structural framing, which is always reconstructed regardless of
// modification).
//
// Every modified write in this file also recomputes File Meta Group Length
// (0002,0000) (see lossless_writer.cpp's compute_file_meta_group_length),
// which is itself a synthesized (regenerated) 4-byte UL value -- so every
// modified-write test below expects 4 extra regenerated bytes beyond
// whatever mutation it's actually testing. That +4 showing up is also a
// live check that group-length recomputation is running, not just noise to
// work around.

using namespace fds_test;
using fds::ElementPath;
using fds::Fidelity;
using fds::ParseOptions;
using fds::Tag;
using fds::Value;
using fds::VR;
using fds::WriteStatus;

TEST_CASE("an unmodified structure counts every value byte as source-backed", "[write-stats]") {
  auto b = make_file_meta("1.2.840.10008.1.2.1");
  b.element_short(0x0010, 0x0020, "LO", "ID1");  // padded to 4 bytes
  b.element_short(0x0008, 0x0060, "CS", "CT");   // already 2 bytes
  std::vector<std::byte> pixels(64, std::byte{0x11});
  b.pixel_data_native("OW", pixels);

  ParseOptions options;
  options.fidelity = Fidelity::Lossless;
  auto result = fds::parse_buffer(b.bytes(), options);

  std::ostringstream out;
  auto write_result = result.structure->write(out);
  REQUIRE(write_result.status == WriteStatus::Success);
  REQUIRE(write_result.regenerated_value_bytes == 0);
  // Every File Meta element's value, "ID1\0" (4), "CT" (2), and the 64-byte
  // Pixel Data payload -- at minimum this many bytes must be source-backed
  // (File Meta itself contributes more; this is a floor, not an exact
  // count, to avoid this test knowing make_file_meta's exact byte layout).
  REQUIRE(write_result.source_backed_value_bytes >= 4 + 2 + 64);
}

TEST_CASE("a modified element's new value counts as regenerated, others stay source-backed",
          "[write-stats]") {
  auto b = make_file_meta("1.2.840.10008.1.2.1");
  b.element_short(0x0010, 0x0020, "LO", "ID1");  // will be replaced
  b.element_short(0x0008, 0x0060, "CS", "CT");   // stays untouched

  ParseOptions options;
  options.fidelity = Fidelity::Lossless;
  auto result = fds::parse_buffer(b.bytes(), options);

  std::vector<std::byte> replacement(10, std::byte{0x41});  // 10 bytes, unrelated to "ID1\0"
  REQUIRE(result.structure->set_value(ElementPath(Tag(0x0010, 0x0020)),
                                       Value::from_owned(replacement)));

  std::ostringstream out;
  auto write_result = result.structure->write(out);
  REQUIRE(write_result.status == WriteStatus::Success);
  REQUIRE(write_result.regenerated_value_bytes == 10 + 4);  // +4: recomputed group length
  // "CT" (2 bytes) plus File Meta's own values must still be source-backed.
  REQUIRE(write_result.source_backed_value_bytes >= 2);
}

TEST_CASE("a newly-inserted element's value counts as regenerated", "[write-stats]") {
  auto b = make_file_meta("1.2.840.10008.1.2.1");
  ParseOptions options;
  options.fidelity = Fidelity::Lossless;
  auto result = fds::parse_buffer(b.bytes(), options);

  REQUIRE(result.structure->set(Tag(0x0018, 0x0050), VR::DS, Value::from_string("1.0 ")));

  std::ostringstream out;
  auto write_result = result.structure->write(out);
  REQUIRE(write_result.status == WriteStatus::Success);
  REQUIRE(write_result.regenerated_value_bytes == 4 + 4);  // +4: recomputed group length
}

TEST_CASE("erasing an element removes its bytes from both counters", "[write-stats]") {
  auto b = make_file_meta("1.2.840.10008.1.2.1");
  b.element_short(0x0009, 0x0010, "LO", "PRIVATE ");  // 8 bytes, will be erased
  b.element_short(0x0008, 0x0060, "CS", "CT");

  ParseOptions options;
  options.fidelity = Fidelity::Lossless;
  auto result = fds::parse_buffer(b.bytes(), options);

  REQUIRE(result.structure->erase(Tag(0x0009, 0x0010)));

  std::ostringstream out;
  auto write_result = result.structure->write(out);
  REQUIRE(write_result.status == WriteStatus::Success);
  // The erased element's 8 bytes must not appear in either bucket -- the
  // only regenerated bytes are the recomputed group length.
  REQUIRE(write_result.regenerated_value_bytes == 4);
  REQUIRE(write_result.source_backed_value_bytes >= 2);  // at least "CT" survives
}

TEST_CASE("value bytes nested inside a sequence item are counted", "[write-stats]") {
  FixtureBuilder item_content;
  item_content.element_short(0x0008, 0x0100, "SH", "12345678");  // 8 bytes, untouched
  auto item = wrap_in_item(item_content);

  auto b = make_file_meta("1.2.840.10008.1.2.1");
  b.sequence_defined(0x0008, 0x1140, static_cast<std::uint32_t>(item.size()));
  b.append(item);

  ParseOptions options;
  options.fidelity = Fidelity::Lossless;
  auto result = fds::parse_buffer(b.bytes(), options);

  // Trigger the modified-write path without touching the nested element, so
  // its 8 bytes must still show up as source-backed.
  REQUIRE(result.structure->set(Tag(0x0018, 0x0050), VR::DS, Value::from_string("1.0 ")));

  std::ostringstream out;
  auto write_result = result.structure->write(out);
  REQUIRE(write_result.status == WriteStatus::Success);
  REQUIRE(write_result.regenerated_value_bytes == 4 + 4);    // new (0018,0050) + group length
  REQUIRE(write_result.source_backed_value_bytes >= 8);       // the untouched nested element
}
